/* Replace with your SQL commands */
CREATE TABLE IF NOT EXISTS user_plan_tasks(
    uid BIGINT NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    pid BIGINT NOT NULL REFERENCES user_plans(pid) ON UPDATE CASCADE ON DELETE CASCADE,
    tid BIGINT NOT NULL REFERENCES tasks(id) ON UPDATE CASCADE ON DELETE CASCADE,
    tdate DATE NOT NULL,
    tstatus INT NOT NULL DEFAULT 0
);