/* Replace with your SQL commands */
CREATE TABLE IF NOT EXISTS user_sessions(
    sid TEXT UNIQUE NOT NULL,
    uid BIGINT NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    lid BIGINT NOT NULL REFERENCES levels(id) ON UPDATE CASCADE ON DELETE CASCADE,
    sissue TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sexpiry TIMESTAMP WITH TIME ZONE DEFAULT (CURRENT_TIMESTAMP + interval '24 hour')::timestamp
);