/* Replace with your SQL commands */
CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY UNIQE NOT NULL,
    uname VARCHAR(50) UNIQUE NOT NULL,
    fname VARCHAR(50) NOT NULL,
    lname VARCHAR(50) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    passwd TEXT NOT NULL,
    regdate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);